# Generated by Django 4.0.1 on 2022-01-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broadcastmodel',
            old_name='video',
            new_name='video_url',
        ),
    ]
